# Generated by Django 4.0.4 on 2022-04-19 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('studentId', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('event', models.CharField(blank=True, max_length=100)),
                ('certificateId', models.CharField(blank=True, max_length=100)),
                ('certificateURL', models.URLField(blank=True, max_length=256)),
            ],
        ),
    ]
